[package]
name = "confy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.6.1"
serde_derive = "1.0.144"
serde = { version = "1.0", features = ["derive"] }